version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accenture-app
    ports:
      - "8000:8000"
    environment:
      SPRING_APPLICATION_NAME: accenture-challenge
      SPRING_DATASOURCE_URL: jdbc:postgresql://accenture-market.cfo2m0coyhe2.us-east-1.rds.amazonaws.com:5432/accenture-market
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Singapur0906*
      SERVER_ADDRESS: 0.0.0.0
      SERVER_PORT: 8000
    restart: always

  nginx:
    image: nginx:latest
    container_name: accenture-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
